bulletin/urls.py
from django.urls import path
from . import views

app_name = 'bulletin'
urlpatterns = [
    # 기본 페이지
    path('', views.bulletin, name='main'),

    # 게시글 조회, 추가, 수정, 삭제
    path('<int:post_id>/', views.post),
    path('upload_post/', views.upload_post, name='upload_post'),
    path('<int:post_id>/modify/', views.modify_post, name='modify_post'),
    path('<int:post_id>/delete/', views.delete_post, name='delete_post'),

    # 댓글 추가, 삭제
    path('add_reply/', views.add_reply, name='add_reply'),
    path('delete_reply/', views.delete_reply, name='delete_reply'),

]

main/urls.py
from django.urls import path
from .views import mypage, detectme
from timer.views import service

urlpatterns = [
    path('', service, name='service'),
    path('mypage', mypage, name="mypage"),
    path('detectme', detectme, name="detectme"),

]

tag/urls.py
from .views import Autocomplete, BasicDALView
from django.urls import path

urlpatterns = [
    path('test/', Autocomplete.as_view(), name='test'),
    path('test2/', BasicDALView, name='test2'),

]

withme/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('tag/', include('tag.urls')),
    path('timer/', include('timer.urls')),
    path('predict_eyes/', include('predict_eyes.urls')),
    path('admin/', admin.site.urls),
    path('calendarApp/', include('calendarApp.urls')),
    path('bulletin/', include('bulletin.urls')),
]

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bulletin/models.py
from django.db import models
from accounts.models import User


# 게시판 피드 객체
class Post(models.Model):
    title = models.CharField(max_length=255, null=True)
    write_date = models.DateTimeField(null=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    image = models.ImageField(null=True, upload_to="community/%Y%m%d", blank=True)
    content = models.TextField(max_length=255, null=True)
    view_count = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def update_counter(self):
        self.view_count = self.view_count + 1
        self.save()


class Reply(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)

main/models.py
from django.db import models


# Create your models here.
class Intro(models.Model):
    intro_text = models.TextField()

bulletin/forms.py
from .models import Post
from django import forms


# 글쓰기 기능 관련 폼 추가
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']

        labels = {'title': '제목', 'content': '내용', 'image': '사진'}

bulletin/views.py
import os
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .models import Post, Reply
from .forms import PostForm
from accounts.models import User
from django.db.models import Q
import json
from uuid import uuid4
from django.utils import timezone


def uuid_name_upload_to(filename):
    ymd_path = timezone.now().strftime('%Y/%m/%d')
    uuid_name = uuid4().hex
    extension = os.path.splitext(filename)[-1].lower()  # 확장자 추출하고, 소문자로 변환
    return '/'.join([
        ymd_path,
        uuid_name[:2],
        uuid_name + extension,
    ])


# Create your views here.
@login_required
def bulletin(request):
    # 입력 파라미터
    page = int(request.GET.get('page', 1))
    keyword = request.GET.get('keyword', '')

    # 게시판 (등록일 기준 최신 순)
    post_list = Post.objects.all().order_by('-write_date')

    # 검색 기능
    if keyword:
        post_list = post_list.filter(
            Q(title__icontains=keyword) | Q(content__icontains=keyword) | Q(user__username__icontains=keyword)
        ).distinct()

    # 한 페이지 당 5개 게시물
    post_count = 5
    paginator = Paginator(post_list, post_count)
    print_range = 5
    start_page = (page - 1) // print_range * print_range + 1
    end_page = min(start_page + (print_range - 1), paginator.num_pages)
    post_obj = paginator.get_page(page)
    context = {'post_list': post_obj, 'current_page': page, 'keyword': keyword,
               'page_range': range(start_page, end_page + 1)}

    return render(request, 'bulletin/main.html', context)


@login_required
def post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    reply_list = Reply.objects.filter(post__id=post_id)
    if request.method == "POST":
        reply = Reply()
        reply.post = Post.objects.get(id=post_id)
        reply.user = request.user
        reply.content = request.POST.get('content')
        reply.created_at = timezone.now()
        if reply.content != '':
            reply.save()

    return render(request, 'bulletin/post.html', {'post': post, 'reply_list': reply_list})


@login_required
def upload_post(request):
    if request.method == "POST":
        print("request:", request)
        post = Post()
        post.title = request.POST['title']
        post.content = request.POST['content']
        try:
            post.image = request.FILES['image']
            post.image.name = uuid_name_upload_to(post.image.name)
            print(post.image.name)
        except ValueError:
            print("\n" * 10)
            print("error")
            print("\n" * 10)

        post.write_date = timezone.now()
        post.user = request.user
        post.save()
        return redirect("../")
    else:
        form = PostForm()

    return render(request, 'bulletin/upload_post.html', {'form': form})


@login_required
def modify_post(request, post_id):
    login_session = request.session.get('login_session', '')
    context = {'login_session': login_session}

    post = Post.objects.get(id=post_id)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.modify_date = timezone.now()

            post.save()
            return redirect('/bulletin/' + str(post.id), context)
    else:
        form = PostForm(instance=post)

    context = {'form': form}
    return render(request, 'bulletin/modify_post.html', context)


@login_required
def delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return redirect('/bulletin')


@login_required
def add_reply(request):
    obj = request.body.decode("utf-8")
    data = json.loads(obj)

    post_id = data['post_id']
    user_id = data['user_id']
    content = data['content']
    if request.method == "POST":
        reply = Reply()
        reply.post = Post.objects.get(id=post_id)
        reply.user = User.objects.get(id=user_id)
        reply.content = content
        reply.created_at = timezone.now()
        if reply.content != '':
            print(reply.content)
            reply.save()

    return JsonResponse(data)


@login_required
def delete_reply(request):
    obj = request.body.decode("utf-8")
    data = json.loads(obj)

    reply_id = data['reply_id']

    target = Reply.objects.get(id=reply_id)
    target.delete()

    return JsonResponse(data)

main/views.py
import base64
import os

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from calendarApp.form import TodoForm, TodoEditForm
from calendarApp.models import Todolist
from django.db.models import Q
from timer.models import UserLog
from tag.models import Tag
import random
from withme.settings import MEDIA_ROOT
from django.utils.dateparse import parse_datetime
import datetime


@csrf_exempt
def detectme(request):
    if request.POST:
        data = request.POST.__getitem__('data')
        data = data[22:]  # data:image/png;base64 부분 제거
        number = random.randrange(1, 10000)

        # 저장 경로 및 파일명 설정
        filename = request.user.username + '_image_' + str(number) + '.png'
        save_path = os.path.join(MEDIA_ROOT, filename)

        image = open(save_path, "wb")  # path+filename, "wb")
        image.write(base64.b64decode(data))
        image.close()

        # 모델 완성 시, 해당 result 반환
        number = random.randrange(1, 10000)
        user_state = '눈 뜨세요' if number % 2 else '화이팅 !!'
        answer = {
            'userState': user_state,
            'filepath': save_path
        }

        return JsonResponse(answer)
    return render(request, 'main/video_test.html')


@login_required
def camera_setting(request):
    item = UserLog.objects.filter(Q(user_id=request.user) & Q(end_time__isnull=True))
    if len(item) == 0:
        return render(request, 'main/camera_setting.html')
    else:
        item = item[0]
        todo_form = TodoForm()
        todo_list = Todolist.objects.all().filter(Q(author=request.user))
        tag = Tag.objects.get(pk=item.tag_id)

        return render(request, 'timer/service_main.html', {
            "todo_form": todo_form,
            "todo_edit_form": TodoEditForm,
            "todo_list": todo_list,
            "tag": tag,
            "user_log": item,
        })


def get_month_data(user, date_str):
    userlog_items = UserLog.objects.filter(end_time__year=date_str[:4], end_time__month=date_str[6:8])
    length = len(userlog_items)  # 굳이 사람으로 나눌 필요 없음. 학습 시간의 전체 평균을 구하면 해당 로그 길이로 나눠도 문제 없음.
    my_total, user_total = 0, 0
    my_focus, user_focus = 0, 0
    user_tag_dict = dict()
    user_log_list = []
    for item in userlog_items:
        parsed_t = parse_datetime(str(item.start_time))
        parsed_t2 = parse_datetime(str(item.end_time))
        tt = int((parsed_t2 - parsed_t).total_seconds())
        ft = tt - item.abnormal_time
        if item.user == user:
            my_total += tt // 60
            my_focus += ft // 60
            user_log_list.append(item)
            tag_str = Tag.objects.get(pk=item.tag_id)
            if user_tag_dict.get(tag_str) is None:
                user_tag_dict[tag_str] = tt // 60
            else:
                user_tag_dict[tag_str] += tt // 60
        user_total += tt // 60
        user_focus += ft // 60

    if length != 0:
        user_total //= length

    if length != 0:
        user_focus //= length
    return my_total, user_total, my_focus, user_focus, user_tag_dict, user_log_list


@login_required
def mypage(request):
    context = dict()
    user = request.user

    now_date = str(datetime.datetime.now().strftime('%Y년 %m월'))
    if request.POST:
        now_date = request.POST['new_date']

    my_total, user_total, my_focus, user_focus, user_tag_dict, user_log_list = get_month_data(user, now_date)
    context['now_date'] = now_date
    context['my_total'] = my_total
    context['user_total'] = user_total
    context['my_focus'] = my_focus
    context['user_focus'] = user_focus
    context['user_tag_dict'] = user_tag_dict
    context['user_log_list'] = user_log_list

    return render(request, 'main/mypage.html', context)

bulletin/templates/bulletin/main.html
{% extends "main/main_base.html" %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'bulletin.css' %}" />

<div class="row" style="color:white;">
    <div>
        <div style="height:140px"></div>
        <h1 class="text-center">
            <p style="font-size: 40px;">Community</p>
        </h1>

    
        <a href='upload_post/' id="btn_write" class="btn btn-outline-light align-self-end mx-2">
            글쓰기
        </a>
        
        <table class="table table-dark table-hover">
            <thead>
                <tr>
                    <th width="50px">번호</th>
                    <th width="200px">제목</th>
                    <th width="100px">글쓴이</th>
                    <th width="150px">시간</th>
                    <th width="70px">조회 수</th>
                </tr>
            </thead>
            <tbody>
                {% for post in post_list%}
                <tr>
                    <td width="50px" style="font-size:10px;">{{post.id}}</td>
                    <td width="200px"><a href="./{{post.id}}" style="font-size:20px; color:white;"><b>{{post.title}}</b></a></td>
                    <td width="100px" style="font-size:15px;">{{post.user.username}}</td>
                    <td width="150px" style="font-size:10px;">{{post.write_date}}</td>
                    <td width="50px" style="font-size:15px;">{{post.view_count}}</td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
        
    
        <div style="height:5px"></div>
        <div class="row justify-content-end my-3" style="margin-left: 0.5px ">
            <div class="col-4 input-group" style='margin: 0 auto'>
                <input type="text" class="form-control keyword" value="{{ keyword|default_if_none:'' }}">
                <div class="input-group-append" style="display: flex; flex-flow: row wrap;">
                    <a id="btn_search" class="btn btn-outline-light align-self-end mx-2">검색</a>
                </div>
            </div>
        </div>
    
        <ul class="pagination justify-content-center">
            
            {% if post_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ post_list.previous_page_number}}">◁</a>
            </li>
            {% endif %}

            {% for page_num in page_range %}
                {% if page_num == current_page%}
                    <li class="page-item active "><a class="page-link" href="?page={{page_num}}">{{page_num}}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{page_num}}">{{page_num}}</a></li>
                {% endif %}
            {% endfor %}

            {% if post_list.has_next%}
            <li class="page-item">
                <a class="page-link" href="?page={{ post_list.next_page_number}}">▷</a>
            </li>
            {% endif %}

        </ul>
    
    
        <form id="searchForm" method="GET" action="{% url 'bulletin:main' %}">
            <input type="hidden" id="keyword" name="keyword" value="{{ keyword|default_if_none:'' }}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
        </form>
    </div>    
</div>

<script type='text/javascript'>
    $(document).ready(function() {
        $(".page-link").on('click', function() {
            $("#page").val($(this).data("page"));
            $("#searchForm").submit();
        });

        $("#btn_search").on('click', function() {
            console.log('test')
            $("#keyword").val($(".keyword").val());
            $("#page").val(1);  // 검색 버튼을 클릭할 경우 1페이지부터 조회한다.
            $("#searchForm").submit();
        });
    });
</script>

{% endblock %}

bulletin/templates/bulletin/modify_post.html
{% extends "main/main_base.html" %}
{% block content %}
{% load static %}

<!--jquery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<link rel="stylesheet" href="{% static 'bulletin.css' %}" />

<div class="row" style="color:white;">
    <div>
        <h5 class="my-5 pb-2">게시글 수정하기</h5>
        <div class="contour"></div>
        <form method="POST" class="post-form my-3">
            {% csrf_token %}
            <!-- 오류표시 Start -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <!-- 오류표시 End -->
            <div class="form-group">
                <label for="title">제목</label>
                <input type="text" class="form-control" name="title"
                    value="{{ form.title.value|default_if_none:'' }}" placeholder="제목을 입력하세요">
                </div>
                <br>
            <div class="form-group">
                <label for="content">내용</label>
                <textarea class="form-control" name="content" rows="10" placeholder="내용을 입력하세요">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <br>
            <input type="submit" id="btn_bulletin" href='../' class="btn btn-outline-light align-self-end mx-2" value="저장하기"/>
            <!-- <button type="submit" class="btn btn-secondary">저장하기</button> -->
        </form>
    </div>
</div>

{% endblock %}

bulletin/templates/bulletin/post.html
{% extends "main/main_base.html" %}
{% block content %}
{% load static %}

<!--jquery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<link rel="stylesheet" href="{% static 'bulletin.css' %}" />

<p hidden>{{ post.update_counter }}</p>
<p hidden>{{ post.view_count}}</p>

<div class="container" style="position: relative;">
    <div class="row">
        <div class="col-12" style="height: 72px">
        </div>
    </div>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-7 bg-light" style="border-radius: 10px 10px 10px 10px / 10px 10px 10px 10px; width: 800px;">
            <br>
            <div>
                <button onclick="location.href= '../'" class="btn btn-secondary" style="float:right; margin-left: 10px; margin-right: 10px;">목록</button>
                <button onclick="location.href='../upload_post/'" class="btn btn-secondary" style="float:right;">글쓰기</button>
            </div>

            <div>
                <br><br>
                {% if post.user.id == user.id %}    
                    <div>
                        <a href="{% url 'bulletin:delete_post' post.id %}" type="button" class="btn btn-default pull-right" style="float: right; margin-right: 10px; margin-bottom: 10px">
                            삭제
                        </a>
                        <a href="{% url 'bulletin:modify_post' post.id %}" type="button" class="btn btn-default pull-right" style="float: right; margin-right: 10px; margin-bottom: 10px">
                            수정
                        </a>
                    </div>
                {% endif %}
                <br>
                <b style="font-size:35px">{{post.title}}</b>   
                <a href="#" aria-label="Left Align" style="color:gray; text-decoration-line:underline">
                        작성자 :    
                        {% if post.user.username %}
                            {{post.user.username}}
                        {% else %}
                            알 수 없음
                        {% endif %}              
                </a>
                <div style="height: 0px; background-color: black"></div>
                <p> time: {{post.write_date}}</p>
                <div class="contour"></div>
                <br><br>
                <!-- 이미지 보여주기 -->
                {% if post.image %}
                    <img src = "{{ post.image.url }}" alt="" height="200">
                    <br>
                {% endif %}
                <p>
                    {% if not post.content %}
                        내용 없음
                    {% else %}
                        {{post.content}}
                    {% endif %}
                </p>  
                <br><br><br><br>
            </div>    
        
            <b>댓글</b>
            <div class="contour"></div>
            <div class="container">
                {% for reply in reply_list %}
                    <b>{{reply.user.username}}</b>  || &nbsp {{reply.content}}                
                    {% if reply.user.id == user.id %}   
                        &nbsp<input type="submit" class = "reply_remove" id="{{reply.id}}" style="font-size:1px; background-color:transparent; border-color:transparent" value="삭제" onclick="remove_reply({{reply.id}})">
                    {% endif %}
                    <br>
                {% endfor %}
            </div>
            <br>
            <div>
                <form method="POST">
                    {% csrf_token %}
                    <input type="text" id="reply_content" class="form-control" style="width:80%; border:none; " placeholder="댓글 입력">
                    {% if user.is_authenticated %}
                        <input type="button" id="reply_add" class="btn btn-basic pull-right" value="저장">
                    {% else %}                    
                        <input type="button" class="btn btn-basic pull-right" value="저장" disabled>
                    {% endif %}
            </div>   
        </div>   
    </div>
</div>
<script>
    function getCookie(name) {
        var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
            }
        }
        return cookieValue;
    }

    document.querySelector('#reply_add').addEventListener('click', () => {
        let content = document.getElementById('reply_content').value;
        let post_id = {{post.id}};
        let user_id = {{user.id}};
        const csrftoken = getCookie('csrftoken');
        console.log(content);
        const data = { 'content': content, 'post_id': post_id, 'user_id': user_id };
        const ajax = axios({
            url: '/bulletin/add_reply/',
            method: 'post',
            data: JSON.stringify(data),
            headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': csrftoken
        }
        });
        ajax.then(function (result) {
            location.reload()            
        });
    });
    
    function remove_reply(reply_id){
        const csrftoken = getCookie('csrftoken');
        console.log(reply_id);
        const data = { 'reply_id': reply_id };
        const ajax = axios({
            url: '/bulletin/delete_reply/',
            method: 'post',
            data: JSON.stringify(data),
            headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': csrftoken
        }
        });
        ajax.then(function (result) {
            location.reload()
        });
    }
    
</script>
{%endblock%}

bulletin/templates/bulletin/upload_post.html
{% extends "main/main_base.html" %}
{% block content %}
{% load static %}
<!--jquery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<link rel="stylesheet" href="{% static 'bulletin.css' %}" />

<div class="row" style="color:white;">
  <div>
    <br>
    <a href='../' id="btn_bulletin" class="btn btn-outline-light align-self-end mx-2">
      목록
    </a>
  
    <div class="contour"></div>

    <form method="POST" class="post-form my-3" enctype="multipart/form-data">
      {% csrf_token %}
    
      <div class="form-group">
        <label for="title">제목</label>
        <input
          type="text"
          class="form-control"
          name="title"
          value=""
        />

        <label for="content">내용</label>
        <textarea class="form-control" id="textbox" name="content" rows="10" value=""></textarea>
        <label for="image">사진</label>
        <input
          type="file"
          class="form-control"
          name="image"
        />
      </div>
        <input type="submit" id="btn_bulletin" href='../' class="btn btn-outline-light align-self-end mx-2" value="저장"/>
      <div><br></div>
    </form>
  </div>
</div>

{%endblock%}