accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", views.login, name="Login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
    path("change_password/", views.change_password, name='change_password'),
    path("change_type/", views.update, name='change_type'),
]

bulletin/urls.py
from django.urls import path
from . import views

app_name = 'bulletin'
urlpatterns = [
    # 기본 페이지
    path('', views.bulletin, name='main'),

    # 게시글 조회, 추가, 수정, 삭제
    path('<int:post_id>/', views.post),
    path('upload_post/', views.upload_post, name='upload_post'),
    path('<int:post_id>/modify/', views.modify_post, name='modify_post'),
    path('<int:post_id>/delete/', views.delete_post, name='delete_post'),

    # 댓글 추가, 삭제
    path('add_reply/', views.add_reply, name='add_reply'),
    path('delete_reply/', views.delete_reply, name='delete_reply'),

]

main/urls.py
from django.urls import path
from .views import mypage, detectme
from timer.views import service

urlpatterns = [
    path('', service, name='service'),
    path('mypage', mypage, name="mypage"),
    path('detectme', detectme, name="detectme"),

]

tag/urls.py
from .views import Autocomplete, BasicDALView
from django.urls import path

urlpatterns = [
    path('test/', Autocomplete.as_view(), name='test'),
    path('test2/', BasicDALView, name='test2'),

]

withme/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('tag/', include('tag.urls')),
    path('timer/', include('timer.urls')),
    path('predict_eyes/', include('predict_eyes.urls')),
    path('admin/', admin.site.urls),
    path('calendarApp/', include('calendarApp.urls')),
    path('bulletin/', include('bulletin.urls')),
]

# 이미지 URL 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models


# Create your models here.
class Intro(models.Model):
    intro_text = models.TextField()

main/views.py
import base64
import os

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from calendarApp.form import TodoForm, TodoEditForm
from calendarApp.models import Todolist
from django.db.models import Q
from timer.models import UserLog
from tag.models import Tag
import random
from withme.settings import MEDIA_ROOT
from django.utils.dateparse import parse_datetime
import datetime


@csrf_exempt
def detectme(request):
    if request.POST:
        data = request.POST.__getitem__('data')
        data = data[22:]  # data:image/png;base64 부분 제거
        number = random.randrange(1, 10000)

        # 저장 경로 및 파일명 설정
        filename = request.user.username + '_image_' + str(number) + '.png'
        save_path = os.path.join(MEDIA_ROOT, filename)

        image = open(save_path, "wb")  # path+filename, "wb")
        image.write(base64.b64decode(data))
        image.close()

        # 모델 완성 시, 해당 result 반환
        number = random.randrange(1, 10000)
        user_state = '눈 뜨세요' if number % 2 else '화이팅 !!'
        answer = {
            'userState': user_state,
            'filepath': save_path
        }

        return JsonResponse(answer)
    return render(request, 'main/video_test.html')


@login_required
def camera_setting(request):
    item = UserLog.objects.filter(Q(user_id=request.user) & Q(end_time__isnull=True))
    if len(item) == 0:
        return render(request, 'main/camera_setting.html')
    else:
        item = item[0]
        todo_form = TodoForm()
        todo_list = Todolist.objects.all().filter(Q(author=request.user))
        tag = Tag.objects.get(pk=item.tag_id)

        return render(request, 'timer/service_main.html', {
            "todo_form": todo_form,
            "todo_edit_form": TodoEditForm,
            "todo_list": todo_list,
            "tag": tag,
            "user_log": item,
        })


def get_month_data(user, date_str):
    userlog_items = UserLog.objects.filter(end_time__year=date_str[:4], end_time__month=date_str[6:8])
    length = len(userlog_items)  # 굳이 사람으로 나눌 필요 없음. 학습 시간의 전체 평균을 구하면 해당 로그 길이로 나눠도 문제 없음.
    my_total, user_total = 0, 0
    my_focus, user_focus = 0, 0
    user_tag_dict = dict()
    user_log_list = []
    for item in userlog_items:
        parsed_t = parse_datetime(str(item.start_time))
        parsed_t2 = parse_datetime(str(item.end_time))
        tt = int((parsed_t2 - parsed_t).total_seconds())
        ft = tt - item.abnormal_time
        if item.user == user:
            my_total += tt // 60
            my_focus += ft // 60
            user_log_list.append(item)
            tag_str = Tag.objects.get(pk=item.tag_id)
            if user_tag_dict.get(tag_str) is None:
                user_tag_dict[tag_str] = tt // 60
            else:
                user_tag_dict[tag_str] += tt // 60
        user_total += tt // 60
        user_focus += ft // 60

    if length != 0:
        user_total //= length

    if length != 0:
        user_focus //= length
    return my_total, user_total, my_focus, user_focus, user_tag_dict, user_log_list


@login_required
def mypage(request):
    context = dict()
    user = request.user

    now_date = str(datetime.datetime.now().strftime('%Y년 %m월'))
    if request.POST:
        now_date = request.POST['new_date']

    my_total, user_total, my_focus, user_focus, user_tag_dict, user_log_list = get_month_data(user, now_date)
    context['now_date'] = now_date
    context['my_total'] = my_total
    context['user_total'] = user_total
    context['my_focus'] = my_focus
    context['user_focus'] = user_focus
    context['user_tag_dict'] = user_tag_dict
    context['user_log_list'] = user_log_list

    return render(request, 'main/mypage.html', context)

main/templates/main/camera_setting.html
{% extends "main/main_base.html" %}
{% load static %}

{% block content %}

<div class="row" style="color:white;">
    <div class="col-9" style="border-radius: 10px 0 0 10px / 10px 0 0 10px;">
        <div class="d-flex flex-column" >
            <div style="height:30px"></div>
            <div class="px-3 mb-2 border-bottom border-light">
                <p style="font-size: 20px; bold ">공부 주제 선택하기</p>
            </div>
            <div class="m-2 p-2 border-top border-bottom">
                <div class="d-flex justify-content-center">
                    <select id="tag_selector" onChange="tag_change_func(this);" style="width:100%" type = "submit" name="Tag" class="selector" data-placeholder="과목선택" data-autocomplete-light-language="ko" data-autocomplete-light-url="http://127.0.0.1:8000/tag/test/" data-autocomplete-light-function="select2"></select>
                </div>
            </div>
            <div class="mt-3 px-3 mb-2 border-bottom border-light">
                <p style="font-size: 20px; bold ">카메라 설정하기</p>
            </div>

            <div class="row m-2">
                <p class="mx-2"> 카메라의 구도를 오른쪽 사진과 유사하게 설정해 주세요! </p>
                <div class="col-6">
                    <div id="videoSection" class="card border-0" style="background:transparent;">
                        <video class="card-img-top" id="videoElement" style="border-radius: 10px 10px 0px 0px / 10px 10px 0px 0px;"></video>
                        <div class="card-footer bg-dark">
                            <div class="d-flex justify-content-center" style="width:100%">
                                <small id="result" style="color: white; font-size: 0.7em;"></small>
                            </div>
                        </div>
                        <canvas id="canvas" width="400" height="300" style="display:None;"></canvas>
                    </div>
                </div>
                <div class="col-6 border" style="border-radius: 10px" style="height:100%;">
                    <img id="sample_picture" src="{% static "assets/img/sample_camera.png" %}" class="img-fluid" />
                </div>
            </div>
        </div>
        <div style="height:30px"></div>
    </div>
    <div class="col-3 my-5" style="border-radius: 0 10px 10px 0 / 0 10px 10px 0;">
        <div class="d-flex align-items-start flex-column" style="height: 100%; width: 100%;">
            <div class="p-2 mt-3" style="border-radius: 10px 10px 0px 0px / 10px 10px 0px 0px;">
                    > 시작하기 앞서
            </div>

            <div class="p-1" style="width: 100%;">
                <div class="p-2">
                    <div class="d-flex flex-column">
                        <div class="d-flex justify-content-between">
                            <div>
                                공부 주제 선택
                            </div>
                            <div>
                                <img id="setting_tag_picture" src="{% static "assets/img/delete-button.png" %}" alt="" width="20" height="20" />
                            </div>
                        </div>
                        <div>
                            <small id="setting_tag_text" class="text-muted" style="color:#bdbdbd !important;">공부 주제를 선택해 주세요.</small>
                        </div>
                    </div>
                </div>
                <div class="bg-light" style="background: linear-gradient(to top, #e8ecf3, 80%, #edeff0); height:5px"></div>
                <div class="p-2 mt-1">
                    <div class="d-flex flex-column">
                        <div class="d-flex justify-content-between">
                            <div>
                                카메라 구도 설정
                            </div>
                            <div>
                                <img id="setting_camera_picture" src="{% static "assets/img/delete-button.png" %}" alt="" width="20" height="20" />
                            </div>
                        </div>
                        <div>
                            <small id="setting_camera_text" class="text-muted" style="color:#bdbdbd !important;">카메라 구도를 재조정 해주세요.</small>
                        </div>
                    </div>
                </div>
                <div class="bg-light" style="background: linear-gradient(to top, #e8ecf3, 80%, #edeff0); height:5px"></div>
            </div>

            <div class="mt-auto py-2 " style="height:130px; width: 100%;">
                <div class="d-grid gap-2" style="height:120px;">
                    <button id="submit-button" type="button" class="btn btn-block btn-secondary my-2 btn-lg">시작하기</button>
                </div>
            </div>
        </div>
    </div>
</div>
<form id='redirection_form' style="display:None;">
    {% csrf_token %}
</form>
<script>
    function tag_change_func(sel) {
        if ($("#tag_selector")[0].value == ''){
            $('#setting_tag_picture').attr("src", '{% static "assets/img/delete-button.png" %}');
            $('#setting_tag_text').text('공부 주제를 선택해 주세요.');
        }
        else{
            tag_idx = $("#tag_selector")[0].value;
            let tag_name = sel.options[sel.selectedIndex].text;
            $('#setting_tag_picture').attr("src", '{% static "assets/img/check.png" %}');
            $('#setting_tag_text').text('"' + tag_name + '" 과목을 선택하셨습니다!');
        }
    }
    $(function() {
        var canvas = document.getElementById('canvas');
        var context = canvas.getContext('2d');
        const video = document.querySelector("#videoElement");

        function setVideo() {
            if (navigator.mediaDevices.getUserMedia) {
                navigator.mediaDevices
                    .getUserMedia({ video: true })
                    .then(function (stream) {
                        video.srcObject = stream;
                        video.play();
                    })
                    .catch(function (errMsg) {
                        console.log(errMsg);
                    });
            }
        }

        function getFrameData() {
            context.drawImage(video, 0, 0, 400, 300);
            var data = canvas.toDataURL('image/png', 1.0);
            context.clearRect(0, 0, video.width, video.height);

            return data;
        }

        function isUserAwake(result){
            return result['userAwakeState'] != '0';
        }

        const FPS = 1;
        const THRESHOLD = 3;
        var count = THRESHOLD;
        var tag_idx = -1;

        function monitorUser() {
            $.ajax({
                type: "POST",
                url: "../predict_eyes/detectme2",
                data: { data: getFrameData() },
                success: function (result) {
                    //console.log(result);
                    if (isUserAwake(result) == false) {
                        count++;
                        if (count >= THRESHOLD) {
                            count = THRESHOLD;
                            $('#setting_camera_picture').attr("src", '{% static "assets/img/delete-button.png" %}');
                            $('#sample_picture').attr("src", '{% static "assets/img/sample_camera_bad.png" %}');
                            $('#result').text('어깨와 눈이 보이도록 카메라를 조정하세요.');
                            $('#setting_camera_text').text('카메라 구도를 재조정 해주세요.');
                            $('#submit-button').attr("class", 'btn btn-block btn-secondary my-2 btn-lg');
                        }
                    } else {
                        count = 0;
                        $('#setting_camera_picture').attr("src", '{% static "assets/img/check.png" %}');
                        $('#sample_picture').attr("src", '{% static "assets/img/sample_camera.png" %}');
                        $('#setting_camera_text').text('카메라 구도가 완벽합니다!');
                        $('#result').text('바른 자세입니다.');
                        if ($("#tag_selector")[0].value != ''){
                            $('#submit-button').attr("class", 'btn btn-block btn-primary my-2 btn-lg');
                        }
                    }
                },
                error: function () {
                    //console.log('통신 실패');
                },
            });
        }

        setVideo()
        setInterval(function () {
            monitorUser();
        }, 1000 / FPS);

        $('#submit-button').click(function() {
            if (count >= THRESHOLD){
                return;
            }

            if ($("#tag_selector")[0].value == ''){
                console.log('Tag None')
                return;
            }

            let f = $("#redirection_form")[0];
            f.setAttribute('method', 'post');
            f.setAttribute('action', '/timer/service');

            let obj = document.createElement('input');
            obj.setAttribute('type', 'text');
            obj.setAttribute('name', 'tag_id');
            obj.setAttribute('value', $("#tag_selector")[0].value);
            f.appendChild(obj);

            f.submit();
        });
    });
</script>

<link href="/static/admin/css/vendor/select2/select2.css" type="text/css" media="screen" rel="stylesheet">
<link href="/static/admin/css/autocomplete.css" type="text/css" media="screen" rel="stylesheet">
<link href="/static/autocomplete_light/select2.css" type="text/css" media="screen" rel="stylesheet">
<script src="/static/admin/js/vendor/select2/select2.full.js"></script>
<script src="/static/autocomplete_light/autocomplete_light.js"></script>
<script src="/static/autocomplete_light/select2.js"></script>
<script src="/static/autocomplete_light/i18n/ko.js"></script>

{% endblock %}

main/templates/main/index_base.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>With me</title>
    <link rel="stylesheet" href="{% static 'spinloder.css' %}"/>
    <link rel="stylesheet" href="{% static 'bootstrap-5.1.3-dist/css/bootstrap.min.css' %}"/>
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <script src="{% static "bootstrap-5.1.3-dist/js/bootstrap.min.js" %}"></script>
    <meta name="theme-color" content="#7952b3">
    <style>
        body {
            background: black;
            background-image: linear-gradient( rgba(0, 0, 0, 0.0), rgba(0, 0, 0, 0.9)),
                url({% static 'assets/img/photo-main_bg.png' %});
            background-attachment: fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
    </style>
    <link rel="stylesheet" href="{% static 'main.css' %}"/>
</head>
<body>
    <div id="loader"></div>
    <div class="bg-image1" ></div>
    <div class="fixed-top" style="height:60px; background:#000000; opacity:0.8;">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="d-flex align-items-center justify-content-between" style="height:60px; width:100%; color:white;">
                    <div class="mx-2">
                        <span class="bold ">Withme </span>
                        <span></span>
                        <a href="https://jewel-rhythm-b6c.notion.site/WithMe-27cb9af4d54348e49bd7211377878935" class="light mx-3" style="color: #cacbde; font-size: medium;">What is this app?</a>
                    </div>
                    <div>
                        <a href="{% url "accounts:signup" %}" class="btn btn-outline-light align-self-end mx-2">
                            Sign up
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-2"></div>
        </div>

    </div>
    <div class="container-fluid" >
        <div class="d-flex justify-content-center">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <script src="https://unpkg.com/typeit@8.4.0/dist/index.umd.js"></script>
</body>

<script>
    window.onload = function() {
        setTimeout(function() {
          $("#loader").css('display', 'none');
        }, 100);
    }
</script>

</html>

main/templates/main/index_login.html
{% extends "main/index_base.html"  %}
{% load bootstrap5 %}

{% block content %}

<div class="d-flex align-items-center justify-content-end" style="width: 40vw; height: 95vh;">
    <div class="d-flex flex-column">
        <div id="intro_meg" class="p-2" style="color:white;"></div>
    </div>
</div>
<div class="d-flex align-items-center justify-content-center" style="width: 40vw; height: 95vh;">
    <div class="d-flex flex-column" style="width:300px; color:white;">
        <div style="height:50px;"></div>
        <form action="" method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-outline-light btn-lg" style="width:100%;">
                Sign in
            </button>
        </form>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
            new TypeIt("#intro_meg").
            type("비록 산의 정상에 이르지 못했다 하더라도</br>\
            그 도전은 얼마나 대견한 일인가.</br>\
            중도에 넘어진다 해도 성실하게 노력하는 사람들을 존경하자.</br></br>\
            자신에게 내재한 힘을 최대한 끊임없이 도전하는 사람.</br>\
            큰 목표를 설정해 놓고 부단히 노력하는 사람은</br>\
            인생의 진정한 승리자인 것이다.</br></br>\
            L.A 세네카.").
            go()
        });
</script>

{% endblock %}

main/templates/main/main_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>With me</title>
    <link rel="stylesheet" href="{% static 'spinloder.css' %}"/>
    <link rel="stylesheet" href="{% static 'bootstrap-5.1.3-dist/css/bootstrap.min.css' %}"/>
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <script src="{% static "jquery-form-4.3.0.min.js" %}"></script>
    <script src="{% static "bootstrap-5.1.3-dist/js/bootstrap.min.js" %}"></script>
     <script src="{% static "anime.min.js" %}"></script>

    <meta name="theme-color" content="#7952b3">
    <style>
        body {
            background: black;
            background-image: linear-gradient( rgba(0, 0, 0, 0.0), rgba(0, 0, 0, 0.9)),
                url({% static 'assets/img/photo-main_bg.png' %});
            background-attachment: fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }
    </style>
    <link rel="stylesheet" href="{% static 'main.css' %}"/>
</head>
<body>
    <div id="loader"></div>
    <div class="bg-image1" ></div>
    <div class="fixed-top" style="height:60px; background:#000000; opacity:0.8;">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="d-flex align-items-center justify-content-center" style="height:60px; width:100%; color:white;">
                    <div></div>
                    <div>
                        <a href="{% url 'bulletin:main' %}" class="light mx-4 text-white">Community</a>
                        <a href="{% url 'service' %}" class="bolder mx-4 text-white" style="font-size:25px;">[ TIMER ]</a>
                        <a href="{% url 'mypage' %}" class="light mx-4 text-white">My Page</a>
                    </div>
                    <div>

                    </div>
                </div>
            </div>
            <div class="col-2" style="padding-top: 10px;">
                <a href="{% url "accounts:logout" %}" class="btn btn-outline-light align-self-end mx-2">
                    Sign out
                </a>
            </div>
        </div>

    </div>
    <div class="container-fluid" >
        <div class="row" style="padding-top: 120px;">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="d-flex align-items-center justify-content-center" style="width: 100%; height: 100%;">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
    <script src="https://unpkg.com/typeit@8.4.0/dist/index.umd.js"></script>
</body>

<script>
    window.onload = function() {
        setTimeout(function() {
          $("#loader").css('display', 'none');
        }, 100);
    }
</script>

</html>

main/templates/main/mypage.html
{% extends "main/main_base.html"  %}
{% load static bootstrap5 %}

{% block content %}
<script>
    function time_to_str(para){
            let hours = parseInt(para/3600),
            minutes = parseInt((para%3600)/60),
            seconds = para%60;

            let str = '';
            if (hours > 0){
                str += hours + '시간 ';
            }
            if (minutes > 0){
                str += minutes + '분 ';
            }

            str += seconds + '초';
            return str;
        }
</script>
<div class="row" style="color:white; z-index: 10; width:100%; border-radius: 10px;">
    <div class="col-7 p-1" style="background: rgba( 0, 0, 0, 0.3 );">
        <div class="d-flex flex-column border border-white" style="border-radius: 10px 10px 0 0 / 10px 10px 0 0 ; background: rgba( 0, 0, 0, 0.3 );">
            <div class="d-flex align-items-center justify-content-between border-bottom" style="width: 100%; height: 50px;">
                <a id="prev_btn" href="#" class="btn btn-outline-light border-0" style="height: 100%; width: 100px; border-radius: 10px 0 0 0px / 10px 0 0 0px; ">
                     <div class="d-flex align-items-center justify-content-center bold" style="width: 100%; height: 100%;">
                        <
                    </div>
                </a>
                <div id="month_lb" style="font-size:1em">
                    {{ now_date|safe }}
                </div>
                <a id="next_btn" href="#" class="btn btn-outline-light border-0" style="height: 100%; width: 100px; border-radius: 0 10px 0 0 / 0 10px 0 0; ">
                    <div class="d-flex align-items-center justify-content-center bold" style="width: 100%; height: 100%;">
                        >
                    </div>
                </a>
            </div>
            <div id="log_list" class="d-flex align-items-start justify-content-center" style="width: 100%; min-height: 500px;">
                <div class="d-flex flex-column border-0 p-2" style="width:100%;">
                    {% for user_log in user_log_list %}
                        {% include "timer/user_log_item.html" %}
                    {% empty %}
                        <div>
                            <div class="p-2">
                                <div class="d-flex flex-column">
                                    <div>
                                        기록된 내용이 없습니다.
                                    </div>
                                    <small class="text-muted p-2"style="color:#bdbdbd !important;">새로운 학습을 진행해주세요!</small>
                                </div>
                                <div style="background: rgba( 255, 255, 255, 0.3 ); height:3px"></div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>
    <div class="col-5 p-1">
        <div class="d-flex flex-column border border-white p-1" style="background: rgba( 0, 0, 0, 0.3 );">
            {% if not user_log_list|length %}
            <div id="total_lb" class="d-flex align-items-center justify-content-center" style="width: 100%; height:100px;">
                통계를 낼 데이터가 없습니다.
            </div>
            {% else %}
            <div id="total_lb" class="d-flex align-items-center justify-content-center pt-4" style="width: 100%;">
                전체학습량
            </div>
            <div id="total_num_lb" class="d-flex align-items-center justify-content-between pt-3" style="width: 100%;">
                <span class="d-flex align-items-center justify-content-center" style="width: 50%; font-size:0.9em">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;나의 평균
                </span>
                <span class="d-flex align-items-center justify-content-center" style="width: 50%; font-size:0.9em">
                    전체 평균&nbsp;&nbsp;&nbsp;
                </span>
            </div>
            <div class="d-flex align-items-center justify-content-around" style="width: 100%;">
                <canvas id="bar-chart"></canvas>
            </div>
            <div class="d-flex align-items-center justify-content-center mt-4" style="width: 100%; height: 20px;">
                공부별 학습량
            </div>
            <div class="d-flex align-items-center justify-content-around mt-2 p-2" style="width: 100%;">
                <canvas id="bar-chart2"></canvas>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<form id='new_from' method="POST" action="/mypage" enctype="multipart/form-data" style="display:None;">
    {% csrf_token %}
    <input id='new_input' type="text" name="new_date" value=""/>
</form>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.3/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script>
    let tag_name_list = [];
    let tag_tt_list = [];

    {% for key, value in user_tag_dict.items %}
    tag_name_list.push('{{key|safe}}');
    tag_tt_list.push('{{value|safe}}');
    {% endfor %}

    {% if user_log_list|length %}
    tag_tt_list.push('');
    new Chart(document.getElementById("bar-chart"), {
        type: 'bar',
        data: {
            labels: ["학습시간", "집중시간", "학습시간", "집중시간"],
            datasets: [
                {
                    label: "Time(minutes)",
                    backgroundColor: ["rgb(76, 183, 252,0.9)", "rgb(252, 76, 132,0.9)", "rgb(76, 183, 252,0.9)", "rgb(252, 76, 132,0.9)",],
                    data: [{{ my_total|safe }}, {{ my_focus|safe }}, {{ user_total|safe }}, {{ user_focus|safe }}, '0'],
                    fontStyle: 'normal',
                    fontFamily: ['NanumSquare', 'sans-serif'],
                }
            ]
            },
        options: {
            legend: { display: false },
            scales: {
                yAxes: [{
                    display: false,
                }],
            },
        }
    });

    new Chart(document.getElementById("bar-chart2"), {
        type: 'horizontalBar',
        data: {
            labels: tag_name_list,
            datasets: [
                {
                    label: "Time(minutes)",
                    backgroundColor: "rgb(255,255,255,0.7)",
                    data: tag_tt_list,
                    fontStyle: 'normal',
                    fontFamily: ['NanumSquare', 'sans-serif'],
                }
            ]
            },
        options: {
            legend: {
                display: false,
            },
            scales: {
                yAxes: [{
                    display: true,
                    ticks:{
                        fontColor: 'rgb(255, 255, 255)',
                    }
                }],
                xAxes: [{
                    display: false,
                }],
            },
        }
    });
    {% endif %}
    $(function() {
        $("#prev_btn").click(function () {
            let f = $("#new_from")[0];
            now_data_str = '{{now_date|safe}}'
            let year = parseInt(now_data_str.substr(0, 4));
            let month = parseInt(now_data_str.substr(6, 2));

            let s = '';
            month -= 1;
            if (month > 9){
                s = "000" + month;
            }
            else{
                s = "0000" + month;
                if (month == 0){
                    year -= 1;
                    month = 12;
                    s = "000" + month;
                }
            }

            new_date_str = year +'년 '+ s.substr(3)+'월';
            let obj = $("#new_input")[0];
            obj.setAttribute('value', new_date_str);

            $("#new_from").submit()
        });

        $("#next_btn").click(function () {
            let f = $("#new_from")[0];
            now_data_str = '{{now_date|safe}}'
            let year = parseInt(now_data_str.substr(0, 4));
            let month = parseInt(now_data_str.substr(6, 2));

            let s = '';
            month += 1;
            if (month > 9){
                s = "000" + month;
                if (month == 13){
                    year += 1;
                    month = 1;
                    s = "0000" + month;
                }

            }
            else{
                s = "0000" + month;
            }


            new_date_str = year +'년 '+ s.substr(3)+'월';
            let obj = $("#new_input")[0];
            obj.setAttribute('value', new_date_str);

            $("#new_from").submit()
        });

    });
</script>
{% endblock %}